import re

filepath = r'E:\MEUS PROGRAMAS\APOLLO_EDIT_WEB\MEMORIA_ATIVA_SISTEMA.md'
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    r'\bMEMRIA\b': 'MEMÓRIA',
    r'\bViso\b': 'Visão',
    r'\bPrincpios\b': 'Princípios',
    r'\bgerao\b': 'geração',
    r'\bvdeos\b': 'vídeos',
    r'\bcaptao\b': 'captação',
    r'\bpblico\b': 'público',
    r'\bAbstrada\b': 'Abstraída',
    r'\bavanadas\b': 'avançadas',
    r'\baudio\b': 'áudio',
    r'\budio\b': 'áudio',
    r'\bsero\b': 'serão',
    r'\busurio\b': 'usuário',
    r'\busurios\b': 'usuários',
    r'\brodaro\b': 'rodarão',
    r'\bcrditos\b': 'créditos',
    r'\bparmetros\b': 'parâmetros',
    r'\bproduo\b': 'produção',
    r'\bAvanado\b': 'Avançado',
    r'\bAbstrao\b': 'Abstração',
    r'\bmxima\b': 'máxima',
    r'\bNo\b': 'Não',
    r'\blgico\b': 'lógico',
    r'\bEdio\b': 'Edição',
    r'\bAutomtica\b': 'Automática',
    r'\bLanamento\b': 'Lançamento',
    r'\bprprios\b': 'próprios',
    r'\bTCNICA\b': 'TÉCNICA',
    r'\bDecises\b': 'Decisões',
    r'\btcnicas\b': 'técnicas',
    r'\bpadres\b': 'padrões',
    r'\bHISTRICO\b': 'HISTÓRICO',
    r'\bEVOLUO\b': 'EVOLUÇÃO',
    r'\bdecises\b': 'decisões',
    r'\breunies\b': 'reuniões',
    r'\bmudanas\b': 'mudanças',
    r'\blies\b': 'lições',
    r'\bAcesso\b': 'Acesso',
    r'\batualizao\b': 'atualização',
    r'\batualizaes\b': 'atualizações',
    r'\bopces\b': 'opções',
    r'\bopo\b': 'opção',
    r'\bpadro\b': 'padrão',
    r'\btranscrio\b': 'transcrição',
    r'\btranscries\b': 'transcrições',
    r'\bsintetizao\b': 'sintetização',
    r'\bconexo\b': 'conexão',
    r'\bverso\b': 'versão',
    r'\bposio\b': 'posição',
    r'\blatncia\b': 'latência',
    r'\bintegrao\b': 'integração',
    r'\borquestrao\b': 'orquestração',
    r'\bcriao\b': 'criação',
    r'\boperao\b': 'operação',
    r'\bmanuteno\b': 'manutenção',
    r'\bcorreo\b': 'correção',
    r'\bateno\b': 'atenção',
    r'\bdireo\b': 'direção',
    r'\bobrigatorio\b': 'obrigatório',
    r'\binformaes\b': 'informações',
    r'\bconfigurao\b': 'configuração',
    r'\bconfiguraes\b': 'configurações',
    r'\bfuno\b': 'função',
    r'\bfunes\b': 'funções',
    r'\batribuio\b': 'atribuição',
    r'\bcrdito\b': 'crédito',
    r'\bsesso\b': 'sessão',
    r'\bsesses\b': 'sessões',
    r'\brelao\b': 'relação',
    r'\bviso\b': 'visão',
    r'\bmquina\b': 'máquina',
    r'\bmquinas\b': 'máquinas',
    r'\batravs\b': 'através',
    r'\balm\b': 'além',
    r'\bboto\b': 'botão',
    r'\bbotes\b': 'botões',
    r'\baes\b': 'ações',
    r'\bpreservao\b': 'preservação',
    r'\bvarivel\b': 'variável',
    r'\bprxima\b': 'próxima',
    r'\bprximas\b': 'próximas',
    r'\bprximo\b': 'próximo',
    r'\bprximos\b': 'próximos',
    r'\btrfego\b': 'tráfego',
    r'\bpgina\b': 'página',
    r'\bcdigo\b': 'código',
    r'\bcdigos\b': 'códigos',
    r'\bbasico\b': 'básico',
    r'\bcrtica\b': 'crítica',
    r'\bcrtico\b': 'crítico',
    r'\bdomnio\b': 'domínio',
    r'\bcontnuo\b': 'contínuo',
    r'\bhistrico\b': 'histórico',
    r'\bconcluido\b': 'concluído',
    r'\bconcludo\b': 'concluído',
    r'\bpadrao\b': 'padrão',
    r'\bpadroes\b': 'padrões'
}

for k, v in replacements.items():
    content = re.sub(k, v, content)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)
print('Memoria Ativa corrigida com script isolado!')
