version: '3.8'

services:
  autoblog:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: autoblog_cms
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./dev.db:/app/dev.db
      - ./public/uploads:/app/public/uploads
      - ./public/exports:/app/public/exports
    environment:
      - NODE_ENV=production
      - PORT=3000
    # Caso você queira limitar o CPU para não travar o VPS quando o FFMPEG rodar:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2048M'
